### PR TITLE
request: avoid quadratic complexity

### PR DESCRIPTION
**Pull request by catenacyber**
When parsing a big input, we should not allocate+memcpy a big Bstr, but use directly the slice.
This was made difficult by rust having the Bstr supporting the slice in the other case go out of scope too early...

cc @cccs-rtmorti 

Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55257

Still https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55370 remains to be fixed in another PR

### CODE REVIEW

**Comment by catenacyber** [comment]
And second commit fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=55370

**Comment by catenacyber** [comment]
@cccs-rtmorti I think this needs an optimization phase of the memory used by `Transaction`

**Comment by cccs-rtmorti** [comment]
Thanks! These all LGTM. Good catch on the `Headers = <Table>` thing. 

For the difficulty in managing the internal `request_header` buffer, I think this kind of thing is a good candidate for offloading onto the calling application - ideally libhtp would never buffer internally at all - but this is for future work. 

As far as multipart parser goes, it would be preferable to just get rid of multipart entirely if it is not used. 

Regarding `htp_config_set_parse_request_cookies()`, I can remove it from the libhtp-rs PR for suricata, and then we can finish removing it from the API here.

**Comment by cccs-rtmorti** [comment]
> @cccs-rtmorti I think this needs an optimization phase of the memory used by `Transaction`

Yes, I agree this is a good idea.

**Comment by catenacyber** [comment]
> As far as multipart parser goes, it would be preferable to just get rid of multipart entirely if it is not used.

@victorjulien, @jasonish what are the plans for this ?

**Comment by catenacyber** [comment]
> Regarding htp_config_set_parse_request_cookies(), I can remove it from the libhtp-rs PR for suricata, and then we can finish removing it from the API here.

I think it is good to keep the whole API as libhtp C for a first version

**Comment by catenacyber** [comment]
>>  I think this needs an optimization phase of the memory used by `Transaction`
> 
> Yes, I agree this is a good idea.

Let me know when you have something.
I would be curious on how you would do this optimization...

**Comment by cccs-rtmorti** [comment]
> > Regarding htp_config_set_parse_request_cookies(), I can remove it from the libhtp-rs PR for suricata, and then we can finish removing it from the API here.
> 
> I think it is good to keep the whole API as libhtp C for a first version

Ok

**Comment by cccs-rtmorti** [comment]
> > > I think this needs an optimization phase of the memory used by `Transaction`
> > 
> > Yes, I agree this is a good idea.
> 
> Let me know when you have something. I would be curious on how you would do this optimization...

I will show you anything I come up with.

**Comment by victorjulien** [comment]
Suricata never used the libhtp multipart support as it already had its own before libhtp got it during some independent development.

**Pull request merged**
